config/routes.rb
Rails.application.routes.draw do
  get 'registrations/new'

  get 'sessions/new'

  root "home#index"
  resources :workouts, only: [:index, :show, :new, :create]
  resources :meals, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create]
  delete 'sessions', to: "sessions#destroy"
  resources :registrations, only: [:new, :create]
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :meals
  has_many :calories, through: :meals
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    binding.pry
    meal = Meal.create(meal_params)
    redirect_to meal
  end

  private
  def meal_params
    params.require(:meal).permit(:food, :calories, :id)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    meal = Meal.create(meal_params)
    redirect_to meal
  end

  private
  def meal_params
    params.require(:meal).permit(:food, :calories, :id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
  end

  def create
    form_fields = params.permit(:name,:username, :password, :password_confirmation)
    @user = User.new(form_fields)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up"
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You have been logged in!"
    else
      @user = User.new
      flash.now[:error] = "Bad Username or Password"
      render :new
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "You have been logged out!"
  end
end

app/controllers/workout_controller.rb
class WorkoutController < ApplicationController
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    workout = Workout.create(workout_params)
    redirect_to workouts
  end

  private
  def workout_params
    params.require(:workout).permit(:activity, :calories_burned, :id)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    workout = Workout.create(workout_params)
    redirect_to workout
  end

  private
  def workout_params
    params.require(:workout).permit(:activity, :calories_burned, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meal_helper.rb
module MealHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/home/index.html.erb
<h1>Welcome to the best calorie tracker in the universe!!</h1>
<p>...this is a digital product created by Ethan</p>
<%= link_to "Track your calories", new_meal_path %>
<%= link_to "Enter a workout", new_workout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalorieTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:error] %>
    <div>Error: <%= flash[:error] %></div>
  <% end %>

  <% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
  <% end %>

  <% if logged_in? %>
    Current user is: <%= current_user.name %>
    <%= link_to "log out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "sign up here", new_registration_path %>
    <%= link_to "sign in", new_session_path %>
    <% end %>
    

<%= yield %>

</body>
</html>

app/views/meals/index.html.erb
<h1>Meal Index</h1>
<%= link_to "Add a new meal", new_meals_path %>
<ul>
  <% @meals.each do |meal| %>
    <li><%= meal.food %></li>
  <% end %>
</ul>

app/views/meals/new.html.erb
<h1>Create a new meal</h1>
<%= form_for @meal do |f| %>
  <div>

  <%= f.label :food %>
  <%= f.text_field :food %>
</div>
  <div>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
</div>


<%= f.submit %>
<% end %>

app/views/meals/show.html.erb
<%= @meal.food %>

<%= @meal.calories %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/workouts/index.html.erb
<h1>Workout Index</h1>
<%= link_to "Add a new workout", new_workout_path %>
<ul>
  <% @workouts.each do |workout| %>
    <li><%= workout.activity %></li>
  <% end %>

app/views/workouts/new.html.erb
<h1>Create a new workout</h1>
<%= form_for @workout do |f| %>
  <div>

  <%= f.label :activity %>
  <%= f.text_field :activity %>
</div>
  <div>
  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>
</div>


<%= f.submit %>
<% end %>

app/views/workouts/show.html.erb
<%= @workout.activity %>

<%= @workout.calories_burned %>